#!/usr/bin/env bash
#
# copyLinksToBin
# Arguments:
# destFolder  (default ~/bin)
# Requires:
# * dd env var, pointing to the root of the local drs-deposit 
# repository
#
# * $dd/src/deployment (which should be in the repository)
# * the destination folder (~/bin default)

mybin=${1:-~/bin}

[ ! -d ${mybin} ] && { echo ${mybin} not found ; exit 1 ; }

[ ! -w ${mybin} ] && { echo ${mybin} not writable ; exit 1 ; }


# Add this if you get 'less' like behavior
# ❯ git config --global pager.branch false
# See https://stackoverflow.com/questions/48341920/git-branch-command-behaves-like-less
git branch
read -p "Press enter to deploy this branch, any other key to quit." okGo

[ ! -z "$okGo" ] && exit 1


find . -type l | awk -F' ' -v mybin=${mybin} '{print "cp -vHrp ", $NF, mybin}' > .tmp
source  .tmp
rm .tmp
#
