x-airflow-dev-build: &airflow-dev-build
  build:
    context: .
    dockerfile: Dockerfile.dev

services:
  airflow-apiserver:
    <<: *airflow-dev-build

  airflow-scheduler:
    <<: *airflow-dev-build

  airflow-dag-processor:
    <<: *airflow-dev-build

    # bc task debugging is in worker, not service, per ghcopilot
  airflow-worker:
    <<: *airflow-dev-build
    # GH copilto wait-for-client may have been suggested because I was attaching to thwe wrong service.
    # Nope, probably still needed. --wait-for-client 
    # One more attempt without wait for client, because of status hash on airflow
    # This is the debug client command
    # 
    command: bash -c "python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m airflow celery worker"
    ports:
    - "5678:5678"
    environment:
      _ARCHIVE_ROOT: /mnt/Archive
    volumes:
      # Uncomment these when testing on a server - this is for local testing.
      - /Users/jkatz/tmp/DRS3/Archive0:/mnt/Archive0
      - /Users/jkatz/tmp/DRS3/Archive1:/mnt/Archive1
      - /Users/jkatz/tmp/DRS3/Archive2:/mnt/Archive2
      - /Users/jkatz/tmp/DRS3/Archive3:/mnt/Archive3
      - /Users/jkatz/tmp/DRS3/staging:/mnt/staging

      - ${AIRFLOW_PROJ_DIR:-.}/utils:/opt/airflow/utils

  airflow-triggerer:
    <<: *airflow-dev-build

  airflow-init:
    <<: *airflow-dev-build

  airflow-cli:
    <<: *airflow-dev-build

  flower:
    <<: *airflow-dev-build