FROM apache/airflow:3.2.1

USER airflow

COPY --chown=airflow:root --chmod=755 scripts/load_secret_env.sh /opt/airflow/scripts/load_secret_env.sh

RUN pip install --no-cache-dir \
    "bdrc-db-models>=2.0.6" \
    "bdrc-db-lib2>=2.0.6" \
    "cryptography>=47.0.0" \
    "pathlib>=1.0.1" \
    "pillow>=12.2.0" \
    "s3pathlib>=2.3.6" \
    "tqdm>=4.67.3" \
    "bdrc-util2" \
    "apache-airflow>=2.0.0" \
    "sphinx" \
    "myst-parser" \
    "docutils" \
    "pip>=26.1.1" \
    "debugpy>=1.8.20" \
    "mypy>=1.11.0" \
    "ruff>=0.6.9"
