#!/usr/bin/env bash
#
# Run this in a Druk:~jimk/bin/links.
# That folder contains links to all the code you need 
# to build batches. However, because I switch git branches,
# I need to keep a stable set of binaries.
# Formerly these were linked to ~jimk/bin, which was in my path.
#
#
# Requirements:
#
# * define dd=root of your local git repository
# * For me on Druk, that's ~/drs-deposit
# * ~/bin/links. A folder of links to the code. See Druk:~jimk/bin/links

pushd $dd/DRS-BATCH-PROCESSING/deployment
git branch
read -p "Press enter to deploy this branch, any other key to quit." okGo

[ ! -z "$okGo" ] && exit 1

mybin=${1:-"~/bin"}

ls -l | awk -F' ' -v mybin=${mybin} '{print "cp -v ", $NF, mybin}' > .tmp
source .tmp
rm .tmp
#
# Back, back, return from whence ye came
popd