#! /usr/bin/env bash -vx
#
# Recovery mode
#
# Assume a mailerrs.txt
# Assume these files exist

export ME=$(basename $0)
export ME_DIR=$(dirname $0)
. ~/bin/setupErrorLog.sh

## HACK ALERT: This var is the same as in deleteAlreadyDepositedSFTP.sh
targetErrRE="Object owner supplied name" #  .* already exists for owner code"


MAIL_TXT=mailerrs.txt
MAIL_DAT=mailerrs.dat
BUILD_LIST_SPEC='buildList*.txt'
ERR_BATCHES=errbatches.dat

cat $MAIL_TXT | parseMail.awk > $MAIL_DAT
#
# get the user and the batch
grep -v "${targetErrRE}" $MAIL_DAT | cut -f3,4 -d'|' | sort -k1 -t'|' > $ERR_BATCHES


## Danger_ assumes BUILD_LIST_SPEC is quoted. The unglobbed version needs to be passed.
autoRecoveryCore $1 $ERR_BATCHES \'$BUILD_LIST_SPEC\'
