#!/usr/bin/env bash
#
# *** DEPRECATED *** use FindUploadbleBatchPaths.sh
##
# Do the steps to getting files ready
#
# BATCH_EXCLUDE_LIST depends on $ddc/AutoRecovery:
# export ERR_BATCHES=dontBuildBatches.txt

export BATCH_EXCLUDE_LIST=dontBuildBatches
export BUILT=build.txt
export VOLUMES=volList.txt
export NODRS=UndepositedVolumes
export FILESIZES=fileSizes.txt
export TARGET=../buildList.txt

echo -n "Get builds ...."
# WARN: the -not-path *~ filter out backup builds. (as of 2018-10-09, makeXXX was backing up old folders)
find $PR/batchBuilds -maxdepth 2 -mindepth 2  -type d -not -path \*~\* > $BUILT
echo "Done"
# filter before doing anything else
[ -f ${BATCH_EXCLUDE_LIST} ] && { grep -v -f ${BATCH_EXCLUDE_LIST} $BUILT >  $VOLUMES ; } || { mv $BUILT  $VOLUMES ;  }
echo -n "Remove Deposited Paths...."
RemoveDepositedVolumePaths.sh $VOLUMES  UndepositedVolumes
echo "Done"
echo -n "Get Cumulative built file counts...."
 GetCumBuiltFileCounts.sh $NODRS > $FILESIZES
echo "Done"
echo -n "Get first 250000....."
awk  -F'[|]' '{ if ( $3 < 250000) print $1 }' $FILESIZES | xargs -n 1 dirname | sort -u >  $TARGET
echo "Done"
