#!/bin/bash -vx
#
# Do the steps to getting files ready
# 2018 VI.17 - batches are moved to $RP/batchbuilds on success, and only if no duplicates
# RemoveDuplicateVolumes.sh > BuildList.txt
# ls $PR/batchBuilds
export BATCH_EXCLUDE_LIST=dontBuildBatches
export BUILT=build.txt
export VOLUMES=volList.txt
export NODRS=UndepositedVolumes
export FILESIZES=fileSizes.txt
export TARGET=../buildList.txt

find $PR/batchBuilds -maxdepth 2 -type d -mindepth 2 > $BUILT
# filter before doing anything eser
[ -f ${BATCH_EXCLUDE_LIST} ] && { grep -v -f ${BATCH_EXCLUDE_LIST} $BUILT >  $VOLUMES ; } || { mv $BUILT  $VOLUMES ;  }
RemoveDepositedVolumePaths.sh $VOLUMES  UndepositedVolumes
 GetCumBuiltFileCounts.sh $NODRS > $FILESIZES

awk  -F'[|]' '{ if ( $3 < 250000) print $1 }' $FILESIZES | xargs -n 1 dirname | sort -u >  $TARGET
