# pyright: reportOptionalMemberAccess=false

import enum
import logging
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, TypeAlias, cast

import const as c
from BdrcDbLib.DrsContext import DrsDbContext
from BdrcDbModels.models import Volumes
from BdrcDbModels.project_manager import (
    MemberTypes,
    ProjectMembers,
    ProjectMemberSteps,
    Projects,
    Steps,
)
from BdrcDbModels.SqlAlchemy_get_or_create import get_or_create
from sqlalchemy import exists, select
from sqlalchemy.orm import Session, aliased, joinedload

# Import your ORM models
# from BdrcDbModels.project_manager import ProjectMembers, ProjectMemberSteps

logger = logging.getLogger(__name__)
# TODO: Use environment variable supported in 
# bdrc-db-lib2>=2.0.7
MY_DB = "qa"  # or 'prod' in production

class PMTarget(enum.StrEnum):
    PROJECT_MEMBER = "project_member"
    PROJECT_MEMBER_STEP = "project_member_step"

AllowedModel: TypeAlias = ProjectMembers | ProjectMemberSteps  # noqa: UP040
ORMIdentity: TypeAlias = int | tuple[Any, ...] | Mapping[str, Any]  # noqa: UP040

TARGET_TO_MODEL: dict[PMTarget, type] = {
    PMTarget.PROJECT_MEMBER: ProjectMembers,
    PMTarget.PROJECT_MEMBER_STEP: ProjectMemberSteps,
}

@dataclass(slots=True)
class pmItem:
    """
    Github copilot generated dataset with self referential ORM.
    ACHTUNG: or as John Prine said "Listen up buster, and listen up good"
    Any dict item you put in extras **MUST** be an attr in the model_cls() of the pmItem
    Because a usage pattern (also generated by GitHub Copilot) is like this:
    (src is the pmItem, v_pmns is the ORM object loaded by pmItem.load())
    for k, val in src.extras.items():
    if hasattr(v_pms, k):
        setattr(v_pms, k, val)

    Usage Notes: 
        for a pmItem with a single primary key, you can use either a scalar or a dict for the o_id.
            For most uses, an integer scalar is sufficient, but you can use a scalar with the key name
                pmItem("x",  {"id": 10}, PMTarget.PROJECT_MEMBER)
        for a pmItem with a compound key, you can use either a tuple or a dict for the o_id.
            Tuple identity:
                pmItem("x", (10, 7), PMTarget.PROJECT_MEMBER_STEP)
            Dict identity:
                pmItem("x", {"project_member_id": 10, "project_step_id": 7}, PMTarget.PROJECT_MEMBER_STEP)
    """
    label: str
    # SQLAlchemy session.get() identity can be scalar PK, tuple for composite PK,
    # or dict keyed by PK attribute names.
    o_id: ORMIdentity
    target: PMTarget
    extras: dict[str, Any] = field(default_factory=dict)

    def model_cls(self) -> type:
        return TARGET_TO_MODEL[self.target]

    def load(self, session: Session) -> AllowedModel | None:
        obj = session.get(self.model_cls(), self.o_id)

        # Strict runtime check: id must resolve to the expected ORM type.
        if obj is not None and not isinstance(obj, self.model_cls()):
            raise TypeError(
                f"pmItem target/type mismatch: target={self.target}, "
                f"id={self.o_id}, got={type(obj).__name__}"
            )
        return obj

def _require_label(value: str | None, context: str) -> str:
    if value is None:
        raise RuntimeError(f"Missing required label for {context}")
    return value

def _get_drs3_step_name(step_name: str) -> Steps:
    """
    Pre-fetch some standard lookup model objects
    """
    with DrsDbContext(MY_DB) as db:
        session: Session = db.get_session()
        transcode_step = select(Steps).where(Steps.s_name == step_name)  # pyright: ignore[reportArgumentType]
        transcode_step = session.execute(transcode_step).scalar_one_or_none()
        if not transcode_step:
            raise RuntimeError(f"{step_name} step not found")
        return transcode_step
DRS3_STAGE_STEP = _get_drs3_step_name(c.STAGE_STEP_NAME)
DRS3_TRANSCODE_STEP = _get_drs3_step_name(c.TRANSCODE_STEP_NAME)

def _get_drs3_project_objects() -> tuple[Projects, MemberTypes, MemberTypes]:
    """
    Pre-fetch some standard lookup model objects
    """
    with DrsDbContext(MY_DB) as db:
        session = db.get_session()
        project_named_drs3 = select(Projects).where(Projects.name == c.DRS3_PROJECT_NAME)  # pyright: ignore[reportArgumentType]
        project = session.execute(project_named_drs3).scalar_one_or_none()
        if not project:
            raise RuntimeError(f"{c.DRS3_PROJECT_NAME} project not found")

        get_work_type_work = select(MemberTypes).where(MemberTypes.m_type == c.PROJECT_MEMBER_TYPE_WORK)  # pyright: ignore[reportArgumentType]
        work_type = session.execute(get_work_type_work).scalar_one_or_none()
        if not work_type:
            raise RuntimeError(f"{c.PROJECT_MEMBER_TYPE_WORK} MemberType not found")

        volume_type = session.execute(
            select(MemberTypes).where(MemberTypes.m_type == c.PROJECT_MEMBER_TYPE_VOLUME)
        ).scalar_one_or_none()
        if not volume_type:
            raise RuntimeError(f"{c.PROJECT_MEMBER_TYPE_VOLUME} MemberType not found")

        return project, work_type, volume_type

DRS3_PROJECT, DRS3_WORK_TYPE, DRS3_VOLUME_TYPE = _get_drs3_project_objects()

# Used only in launching DAGS.
def get_next_work_pm_for_step(project_step: Steps, prerquisite_step: Steps | None = None) -> pmItem | None:
    results = get_work_pm_for_step(project_step, prerquisite_step, limit=1)
    return results[0] if results else None

# used only in launching DAGs.
def get_work_pm_for_step(project_step: Steps, prerequisite_step: Steps | None = None, limit: int = 1) -> list[pmItem]:
    """
    Get ProjectMembers for a work for which project_step has not been
    run on any of its volumes.
    Returns an empty list if no such work is found.
    
    :param project_step: the Steps instance for the staging step
    :type project_step: Steps
    :param prerequisite_step: optional prerequisite step that must be completed on all volumes
    :type prerequisite_step: Steps | None
    :param limit: maximum number of candidate work project members to evaluate
    :type limit: int
    :return: list of pmItem for the next works, or an empty list if no such work is found
    """
    work_pm_items: list[pmItem] = []
    with DrsDbContext(MY_DB) as db:
        session: Session = db.get_session()

        # Select Work project members where no child volume has a ProjectMemberSteps
        # row for the provided step.

        WorkPM = aliased(ProjectMembers)
        VolumePM = aliased(ProjectMembers)

        # Get all work-level ProjectMembers rows for DRS3 where there is no
        # ProjectMemberSteps row for `project_step` attached to any volume whose
        # Volumes.workId matches that work.
        stmt = (
            select(WorkPM)
            .where(
                WorkPM.project == DRS3_PROJECT, 
                WorkPM.pm_type == DRS3_WORK_TYPE,
                ~exists(
                    select(1)
                    .select_from(ProjectMemberSteps)
                    .join(VolumePM, ProjectMemberSteps.project_member_id == VolumePM.id)
                    .where(
                        ProjectMemberSteps.step_id == project_step.id,
                        VolumePM.project == DRS3_PROJECT,
                        VolumePM.pm_type == DRS3_VOLUME_TYPE,
                        VolumePM.pm_work_id == WorkPM.pm_work_id,  # correlate to outer work PM
                    )
                ),
            )
            .order_by(WorkPM.id)
            .limit(limit)
        )
        candidate_work_dtos = session.scalars(stmt).all()

        if prerequisite_step:
            for candidate_work_dto in candidate_work_dtos:
                # A candidate is valid only if every volume for the work has a
                # successful prerequisite step recorded.
                # Look at volume project members that belong to:
                # the DRS3 project,
                # the volume member type,
                # and the same work as the current candidate work.
                # Keep only volumes for which there is no matching ProjectMemberSteps
                # row where:
                # - the step is the prerequisite step,
                # - and that step has an end time (meaning it finished, regardless of success/failure).
                # So effectively: “Find volumes in this work that do *not* (~exists) have 
                # not completed the prerequisite step.”
                # For drs-deposit#126, this setp was changed so that only the end time is considered:
                # We don't want to include works that are in process, and we don't care if the volumes have failed.
                # This seems a little counterintuitive, but the code to count all the succeses
                # is frighteningly complex.
                missing_prereq_stmt = (
                    select(1)
                    .select_from(VolumePM)
                    .where(
                        VolumePM.project == DRS3_PROJECT,
                        VolumePM.pm_type == DRS3_VOLUME_TYPE,
                        VolumePM.pm_work_id == candidate_work_dto.pm_work_id,
                        ~exists(
                            select(1)
                            .select_from(ProjectMemberSteps)
                            .where(
                                ProjectMemberSteps.project_member_id == VolumePM.id,
                                ProjectMemberSteps.step_id == prerequisite_step.id,
                                #jimk drs-deposit#126 - we want to exc;ude any that have been completed,
                                # regardless of success status (used to check for return_code = 0)
                                ProjectMemberSteps.project_step_end_time.is_not(None)
                            )
                        ),
                    )
                )

                missing_prereq_volume = session.execute(missing_prereq_stmt).first()
                # This is the key part - if there is a row that has not completed (~exists(....)), there will
                # be a row present. If there is such a row, then this work is not a candidate.
                # If there is no such row, then all volumes have completed the prerequisite step,
                # and this work is a candidate.
                if not missing_prereq_volume:
                    _work_pm: pmItem =  pmItem(
                            _require_label(candidate_work_dto.work.WorkName, "work project member"),
                            candidate_work_dto.id,
                            PMTarget.PROJECT_MEMBER,
                        )
                    work_pm_items.append(_work_pm)

                    # Create the ProjectMemberStep for this work
                    # Bug - for sql get or create, you only supply the key fields
                    # in the call - because all parameters are searched for, including
                    # runtime constructs
                    work_pms, is_new = get_or_create(
                        session,
                        ProjectMemberSteps,
                        project_member = candidate_work_dto,
                        project_step=project_step,
                    )
                    logger.info(f"{'Created' if is_new else 'Found'} ProjectMemberSteps for work "
                                f"{candidate_work_dto.work.WorkName}")
                    if is_new:
                        session.commit()


        if not work_pm_items:
            logger.warning(f"No unstaged work found for step {project_step.s_name} with successful" 
                           f"prerequisite step {prerequisite_step.s_name} on all volumes")
        return work_pm_items


def get_pms_for_step(
    work_pm_item: pmItem, work_source_root: Path, project_step: Steps
) -> tuple[pmItem, list[pmItem]]:
    """
    Get or create all the ProjectMemberSteps for the volumes of this work
    that need to be operated on, and return them as a list
    :param work_pm_item: the pmItem instance for the work to stage
    :type unstaged_work_pm_item: pmItem
    :param work_source_root: the root directory for the source files of a work
    :type work_source_root: Path
    :param project_step: the Steps instance for the staging step
    :type project_step: Steps
    :return: list of pmItem for the volumes to stage
    :rtype: list[pmItem]
      """

    unstaged_volumes_pms_items: list[pmItem] = []
    with DrsDbContext(MY_DB) as db:
        session: Session = db.get_session()

        unstaged_work_pm: ProjectMembers = cast(ProjectMembers, work_pm_item.load(session))
        if not unstaged_work_pm:
            raise RuntimeError(
                f"ProjectMember not found for {work_pm_item.label} "
                f"(id={work_pm_item.o_id})"
            )

        # Create the staged step for the work ProjectMember
        unstaged_work_pms: ProjectMemberSteps 
        unstaged_work_pms, is_new = get_or_create(
            session,
            ProjectMemberSteps,
            project_member=unstaged_work_pm,
            project_step=project_step
        )
        session.flush()
        unstaged_work_pms_item : pmItem = pmItem(
            _require_label(unstaged_work_pm.work.WorkName, "work project member step"),
            {"project_member_id": unstaged_work_pm.id, "step_id": project_step.id},
            PMTarget.PROJECT_MEMBER_STEP
        )
    
        images_root = c.get_work_image_path(work_source_root)
        image_dirs = [d for d in images_root.iterdir() if d.is_dir()] if images_root.exists() else []

        # Get the ProjectMembers for the volumes in this work
        get_volume_pm_s_for_work_stmt = (
            select(ProjectMembers)
            .options(joinedload(ProjectMembers.volume))
            .where(
                ProjectMembers.project == DRS3_PROJECT,
                ProjectMembers.pm_type == DRS3_VOLUME_TYPE,
                ProjectMembers.volume.has(Volumes.workId == unstaged_work_pm.pm_work_id),  # pyright: ignore[reportArgumentType]
            )
        )
        #
        volume_pm_s_for_work = session.scalars(get_volume_pm_s_for_work_stmt).all()

        for image_dir in image_dirs:      

            # select this volume from ProjectMembers by matching folder name
            volume_pm = next(
                (
                    pm
                    for pm in volume_pm_s_for_work
                    if pm.volume is not None and pm.volume.label == image_dir.name
                ),
                None,
            )
            if not volume_pm:
                raise RuntimeError(
                    "Volume PM not found for volume with label "
                    f"{image_dir.name} in work {unstaged_work_pm.work.WorkName}"
                )
            
            # get_or_create session.flush() es, generating an id.
            volume_pms, is_new = get_or_create(
                session,
                ProjectMemberSteps,
                project_member=volume_pm,
                project_step=project_step
            )

            # Add the 
            unstaged_volumes_pms_items.append(
                pmItem(
                    _require_label(
                        volume_pm.volume.label if volume_pm.volume is not None else None,
                        "volume project member step",
                    ),
                    {"project_member_id": volume_pm.id, "step_id": project_step.id},
                     PMTarget.PROJECT_MEMBER_STEP)
            )
        session.commit()
    return unstaged_work_pms_item, unstaged_volumes_pms_items

def update_database_from_pm_items(work_pms_item: pmItem, volume_pms_items: list[pmItem]) -> None:
    """
    Complete any process for a work item and its associated volumes.
    :param work_pms_item: pmItem for the work being processed, updated out of context
    :param volume_pms_items: list of pmItems for the volumes that were processed, 
    containing opaque user data updated out of context.
    :type work_pms_item: pmItem
    :type volume_pms_items: list[pmItem]

    """

    with DrsDbContext(MY_DB) as db:
        session = db.get_session()
        upd_ok: bool = True

        # Fold in anything that was added to the pmItems
        for v_pms_item in volume_pms_items:
            try:
                v_pms = v_pms_item.load(session)
                for k, val in v_pms_item.extras.items():
                    if hasattr(v_pms, k):
                        setattr(v_pms, k, val)
                
            except Exception as e:
                upd_ok = False
                logger.error(f"Error updating volume pmItems: {v_pms_item.label} (id={v_pms_item.o_id}) Exc: {e}")

        loaded_work_pms = work_pms_item.load(session)
        if not isinstance(loaded_work_pms, ProjectMemberSteps):
            raise RuntimeError(
                f"Work pmItem did not resolve to ProjectMemberSteps: "
                f"{work_pms_item.label} (id={work_pms_item.o_id})"
            )
        db_work_pms: ProjectMemberSteps = loaded_work_pms
        for k, val in work_pms_item.extras.items():
            if hasattr(db_work_pms, k):
                setattr(db_work_pms, k, val)
        if not upd_ok:
            db_work_pms.project_step_result_code = 1
        session.commit()

# drs-deposit#126 - may be obsoleted. 
def get_next_work_to_transcode() -> pmItem | None:
    """
    Get the next work item that has been staged but not yet transcoded.
    Returns None if no such work is found.
    """
    _t_step = _get_drs3_step_name(c.TRANSCODE_STEP_NAME)
    _s_step = _get_drs3_step_name(c.STAGE_STEP_NAME)
    return get_next_work_pm_for_step(_t_step, _s_step)

def get_work_pm_from_name(work_name: str) -> pmItem | None:
    """
    Get the ProjectMembers row for a specific work by name.
    Returns a pmItem projection if the work is found, 
    None otherwise.
    """
    with DrsDbContext(MY_DB) as db:
        session: Session = db.get_session()
        stmt = (
            select(ProjectMembers)
            .where(
                ProjectMembers.project == DRS3_PROJECT,
                ProjectMembers.pm_type == DRS3_WORK_TYPE,
                ProjectMembers.work.has(WorkName=work_name),  # pyright: ignore[reportArgumentType]
            )
            .order_by(ProjectMembers.id)
        )
        work_pm = session.scalars(stmt).first()
        if not work_pm:
            logger.info(f"Work not found in project members: {work_name}")
            return None

        return pmItem(
            _require_label(work_pm.work.WorkName, "work project member"),
            {"id": work_pm.id},
            PMTarget.PROJECT_MEMBER
        )
