INSERT INTO `drs`.`DRS`
(`DRSid`,
`BuildDate`,
`BuildPath`,
`BuildRC`,
`IngestDate`,
`objectid`,
`create_time`,
`update_time`,
`DRSdir`,
`objectUrn`,
`filesCount`,
`size`,
`DRScol`,
`volumeId`,
`DRScol1`)
VALUES
(<{DRSid: }>,
<{BuildDate: }>,
<{BuildPath: }>,
<{BuildRC: -1}>,
<{IngestDate: }>,
<{objectid: }>,
<{create_time: CURRENT_TIMESTAMP}>,
<{update_time: }>,
<{DRSdir: }>,
<{objectUrn: }>,
<{filesCount: }>,
<{size: }>,
<{DRScol: }>,
<{volumeId: }>,
<{DRScol1: }>);
